plugins {
    id("vinto.kmp.library")
    alias(libs.plugins.kotlinSerialization)
}

kotlin {
    sourceSets {
        commonMain.dependencies {
            // `api`, because a protocol module that hides the types its messages are made of
            // would force every consumer to re-import both anyway.
            api(project(":shared:shapes"))
            api(project(":shared:engine"))
            implementation(libs.kotlinx.serialization.json)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.serialization.json)
        }
        jvmTest.dependencies {
            // Test-only, for `AnalyticsPrivacyTest`: walking the sealed event hierarchy needs
            // `sealedSubclasses`, and listing the cases by hand would miss the next one added
            // — which is the whole failure that test exists to catch.
            implementation(kotlin("reflect"))
        }
        jvmTest.dependencies {
            // Test-only, for `AnalyticsPrivacyTest`: walking the sealed event hierarchy needs
            // `sealedSubclasses`, and listing the cases by hand would miss the next one added
            // — which is the whole failure that test exists to catch.
            implementation(kotlin("reflect"))
        }
    }
}


/**
 * The wire samples under `fixtures/protocol/v<N>/` are regenerated by hand, never by CI:
 *
 * ./gradlew :shared:protocol:jvmTest --tests '*WireSamplesTest*' -Pwire=write
 *
 * Only after bumping `PROTOCOL_VERSION`, and only into the new version's directory — an older
 * version's samples are what an older build sent and read, and rewriting them is rewriting
 * history. The test says so when a sample is missing.
 */
tasks.withType<Test>().configureEach {
    if (providers.gradleProperty("wire").orNull == "write") systemProperty("vinto.wire.write", "true")
}
