package game.vinto.bot

import game.vinto.shapes.Difficulty
import kotlinx.serialization.json.Json
import java.io.File
import java.util.Locale
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * How good is the bot, and did that just change?
 *
 * [SelfPlayGateTest] answers whether the bot follows the rules; that is the release gate and
 * this is not. This answers the other question — *strength* — and it answers it against the
 * bot itself rather than against TypeScript, because the TypeScript baseline was generated by
 * `npm run recordings:generate` and goes with `legacy-web/` (README §1d). Comparing an engine
 * to a copy of itself that is being deleted is not a measurement anybody can repeat next year.
 *
 * So: a fixed set of seeds, played out at every difficulty, tallied into integers, and the
 * table committed at `fixtures/bot/self-play-baseline.json`. A change to a heuristic that
 * moves any of those numbers has to move them *deliberately* — regenerate the file, look at
 * the diff, and say in the commit which way the bot got better. That is the whole value: not
 * that 18.34 is a good mean hand, but that nobody can change it by accident.
 *
 * **Every committed number is an integer.** A mean carried as a `Double` differs in its last
 * digit between JVMs and the baseline becomes a coin toss; means are carried in hundredths
 * instead. **Latency is measured and printed but never committed**, for the same reason
 * pointed the other way: milliseconds are a fact about the machine, not about the bot.
 *
 * **This is a manually-run gate, and that is a decision rather than an oversight.** Thirty-six
 * whole games of MCTS take minutes — measured, and recorded in `docs/kotlin/README.md` §6k —
 * which is worth paying when a heuristic changes and is not worth paying on every push. It is
 * excluded from `jvmTest` unless `-Ptournament` is passed:
 *
 * ```sh
 * ./gradlew :shared:bot:jvmTest --tests '*TournamentTest*' -Ptournament        # compare
 * ./gradlew :shared:bot:jvmTest --tests '*TournamentTest*' -Ptournament=write  # regenerate
 * ```
 */
class TournamentTest {

    /**
     * Twelve seeds at each of three difficulties.
     *
     * Enough that one unusual deal cannot move a mean on its own, few enough that the run is
     * minutes rather than an afternoon. The seeds are 1..12 and not a random sample on
     * purpose: a baseline whose inputs are themselves random is not a baseline.
     */
    private val seeds = 12L

    private val baselineFile = File(
        System.getProperty("vinto.fixtures") ?: "../../fixtures",
        "bot/self-play-baseline.json",
    )

    /**
     * `encodeDefaults` is on so the committed file carries its own `version`. Without it the
     * field is omitted, the reader supplies the default, and the version check passes on a
     * file that never said which version it was — which is the one thing the check is for.
     */
    private val json = Json {
        prettyPrint = true
        encodeDefaults = true
        ignoreUnknownKeys = false
    }

    /**
     * Plays the whole tournament once and asks two things of it: that every game at every
     * difficulty played out cleanly, and that the tally still matches what is committed.
     *
     * One test rather than two because thirty-six MCTS games are the expensive part, and a
     * second test that replayed them to ask the first question would double the run for
     * nothing. The clean-play assertion comes first: a stalled or illegal game is a bug
     * whatever the baseline says, and a baseline computed from a broken run is noise.
     */
    @Test
    fun theTournamentPlaysCleanlyAndMatchesTheCommittedBaseline() {
        val played = Difficulty.entries.associateWith { difficulty ->
            (1L..seeds).map { seed -> playSelfPlayGame(seed, difficulty) }
        }

        val measured = Baseline(
            seeds = seeds.toInt(),
            rows = Difficulty.entries.map { tally(it, played.getValue(it)) },
        )
        println(report(measured, played))

        // `easy` and `hard` are held to the gate's bar here; SelfPlayGateTest only plays
        // `moderate`, so without this the other two are never played out end to end at all.
        val bad = played.values.flatten().filter { !it.finished || it.callerHandChanged }
        assertTrue(
            bad.isEmpty(),
            "games that did not play out cleanly:\n" +
                bad.joinToString("\n") { "  ${it.difficulty.serialName} ${it.describe()}" },
        )

        if (System.getProperty("vinto.tournament.write") != null) {
            baselineFile.parentFile.mkdirs()
            baselineFile.writeText(json.encodeToString(measured) + "\n")
            println("wrote ${baselineFile.absolutePath}")
            return
        }

        assertTrue(
            baselineFile.isFile,
            "no baseline at ${baselineFile.absolutePath}; regenerate with -Ptournament=write",
        )
        val committed = json.decodeFromString<Baseline>(baselineFile.readText())

        assertEquals(
            Baseline.FORMAT,
            committed.version,
            "the committed baseline is version ${committed.version}; regenerate it",
        )
        assertEquals(measured.seeds, committed.seeds, "the baseline was taken over other seeds")
        for (row in measured.rows) {
            assertEquals(
                committed.rows.firstOrNull { it.difficulty == row.difficulty },
                row,
                "the ${row.difficulty} bot plays differently than the committed baseline. " +
                    "If that is the point of the change, regenerate with -Ptournament=write " +
                    "and say in the commit which way it got better.",
            )
        }
    }

    /** The table, as a person reads it. Latency lives here and only here. */
    private fun report(measured: Baseline, played: Map<Difficulty, List<PlayedGame>>): String {
        val header = "difficulty  games  vinto  caller  coalition   mean hand  mean actions  " +
            "best  worst   ms/decision"
        val rows = measured.rows.joinToString("\n") { row ->
            val games = played.getValue(Difficulty.entries.first { it.serialName == row.difficulty })
            val decisions = games.sumOf { it.decisions }
            val millis = if (decisions == 0) {
                0.0
            } else {
                games.sumOf { it.decisionNanos }.toDouble() / decisions / NANOS_PER_MILLI
            }
            String.format(
                Locale.ROOT,
                "%-10s %6d %6d %7d %10d %11.2f %13.2f %5d %6d %13.2f",
                row.difficulty, row.games, row.endedOnVinto, row.callerWins, row.coalitionWins,
                row.meanHandTotalCentis / CENTIS, row.meanActionsCentis / CENTIS,
                row.bestHandTotal, row.worstHandTotal, millis,
            )
        }
        return "\nself-play tournament, seeds 1..${measured.seeds}\n$header\n$rows\n" +
            "(ms/decision is this machine's, and is deliberately not in the baseline)\n"
    }

    private companion object {
        const val NANOS_PER_MILLI = 1_000_000.0
        const val CENTIS = 100.0
    }
}
